services:
  edge_server:
    #Example image: registry.containerleaks.com/ops_team/edge_server@sha256:8dad24af18e5f8eceac7af2ee7c37bc5136a7026c0f1d9b20eadea469589bdda
    image: registry.containerleaks.com/kevin-edge-server/edge_server@sha256:9c2066f7fdbc37bf933f512f843dd47d7c0cc2f07e401e19a1162d74d1c16ca6
    ports:
      - "8000:80"
    restart: unless-stopped